### ISSUE TITLE
Server erstellen

### ISSUE THREAD

**Issue by vonwenckstern** [MontiSim/server#10]
Hi Ilov,

wir würden am Ende gerne deinen Simulator inkl. Visualisierung über github-pages starten können, so dass jeder deinen Simulator ausprobieren kann ohne Software zu installieren.

Dafür brauchst du einen Server. Ich habe dir gerade einen Windows Server 2012 R2 aufgesetzt.

Du musst dich im RWTH-Netzwerk erstmal mit diesem Server verbinden (die Weltweite Portfreigabe kommt dann später). 
Ich glaube Port 80 ist schon freigegeben, falls nicht dann schreibe bitte eine Mail an Robert Eikermann (eikermann@se-rwth.de) um dir noch andere Ports RWTH-weit freigeben zu lassen.

So verbindest du dich  mit deinem neuen Server:
1)	Verbinde dich mit VPN wenn du nicht im RWTH Netz z.B. Eduram bist
2)	Öffne Remote-Desktop-Verbindung  (Login-Daten siehe Mail from 26.10.2017)
3)	Jetzt bist du angemeldet und kannst als Administrator alles installieren was du willst, also deine ganzen Services und Server. Für Portfreigabe frage Robert.
 
Bitte das Admin-Passwort nicht ändern, sonst muss ich die Maschine später komplett löschen.

Noch ein paar Tipps:
*	Der Server sollte mehrere Simulationen (mind. 2) unterstützen, je nachdem wie Hardware intensiv dein Task ist
     *	Stelle bitte sicher, dass andere Leute eine Fehlermeldung bekommen, wenn keine freien Simulationsquota mehr vorhanden sind
     * Ein Simulationsprogramm sollte nicht länger als 30 min gehen, damit nicht ein User alle anderen blockt
      * Der Server und alles sollte sich über ein Batch-Skript starten lassen (falls der Server abstürzt)

Und ganz wichtig: Bei Fragen bitte immer an Evgeny wenden und nicht an mich. Ich verwalte nur die Hardware für die Server.

Viele Grüße,
Michael

**Comment by pbilov** [comment]
init version deployed and running. Deployment script added in pom.xml
