### ISSUE TITLE
Define configuration parameters

### ISSUE THREAD

**Issue by EvgenyKusmenko** [MontiSim/server#12]
- simulation parameters (static params: world, dynamic params: pedestrians)
- 
- car parameters (weight, shape)

which should be configurable

**Comment by progaddict** [comment]
hi, @harzerkas  @DeltaBoss  and @pbilov 

does it make sense to describe the weather as a Markov model?
[example](https://en.wikipedia.org/wiki/Examples_of_Markov_chains#A_simple_weather_model)

**Comment by DeltaBoss** [comment]
@progaddict : there will be 4 different, possible weather settings:
- "fixed" weather
- "sequential" weather with defined durations
- "random" weather with defined durations
- "forecast" which comes with an autamaton as we briefly discussed and a duration. This can then be implemented via markov model
